AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: 10.0.1.0/24

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow access to Fargate container"
      VpcId: !Ref MyVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyFargateTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "my-fargate-task"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: my-container
          Image: <account-id>.dkr.ecr.<region>.amazonaws.com/my-docker-image:latest
          Essential: true
          EntryPoint: ["/sbin/tini", "--", "/usr/local/bin/entrypoint.sh"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/my-fargate-task
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          LinuxParameters:
            Capabilities:
              Add:
                - SYS_PTRACE
          NetworkConfiguration:
            AwsvpcConfiguration:
              AssignPublicIp: ENABLED
              Subnets:
                - !Ref MySubnet
              SecurityGroups:
                - !Ref MySecurityGroup

  MyFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyFargateTask
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref MySubnet
          SecurityGroups:
            - !Ref MySecurityGroup
